### ISSUE TITLE
Optimize the message structure between the client and the server

### ISSUE THREAD

**Issue by rjman-ljm** [Rustops/no-name-card-game#26]
Enumerate commonly used message types, such as：
+ `ChatMessage`
  > Non-functional
+ `OrderMessage (S2C)`
  > some instruction commands, [StartGame], [GameOver]
+ `SystemMessage`
  > The message from the lobby, similar to the log.

**Comment by hacpy** [comment]
I think the server messages should be handled in a separate system rather than in the chat system, which could also be prepared for the subsequent info_box.
